services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  backend:
    platform: "linux/amd64"   # 👈 acá
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    platform: "linux/amd64"   # 👈 y acá
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  mongo_data:
